version: '3.3'
services:
  server:
    build:
      context: docker/server
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/project/src/
      - ./.git:/var/project/.git/
    env_file: .env
